plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline
app: serverless-basic
service: serverless-basic
useDotenv: true
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: ${env:REGION}
  timeout: 30
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${env:REGION}:*:*'
  environment:
    IS_OFFLINE: ${env:IS_OFFLINE}
    DYNAMO_ENDPOINT: ${env:DYNAMO_ENDPOINT}
    REGION: ${env:REGION}

custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4002
  serverless-dynamodb:
    stages:
      - local
    start:
      docker: true
      port: 8010
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    seed:
      test:
        sources:
          - table: usersTable
            rawsources: [./dynamodb-tables/usersTable-data.json]
          - table: carouselSlidesTable
            rawsources: [./dynamodb-tables/carouselSlidesTable-data.json]
          - table: questionsTable
            rawsources: [./dynamodb-tables/questionsTable-data.json]
          - table: authTable
            rawsources: [./dynamodb-tables/authTable-data.json]

functions:
  hello-world:
    handler: src/handlers/hello/hello.handler
    description: 'offline example'
    events:
      - httpApi:
          path: /${self:provider.stage}/hello
          method: GET
          cors: true
  getUsers:
    handler: src/handlers/users/queryUsers.handler
    description: 'Get active users'
    events:
      - httpApi:
          path: /${self:provider.stage}/users
          method: GET
          cors: true
    environment:
      TABLE_NAME_USERS: ${env:TABLE_NAME_USERS}
  createUser:
    handler: src/handlers/users/createUser.handler
    events:
      - httpApi:
          path: /${self:provider.stage}/users
          method: POST
          cors: true
    environment:
      TABLE_NAME_USERS: ${env:TABLE_NAME_USERS}
      TABLE_NAME_AUTH: ${env:TABLE_NAME_AUTH}
  getCarouselSlides:
    handler: src/handlers/carouselSlides/queryCarouselSlides.handler
    description: 'Get carousel slides'
    events:
      - httpApi:
          path: /${self:provider.stage}/carouselSlides
          method: GET
          cors: true
    environment:
      TABLE_NAME_SLIDES: ${env:TABLE_NAME_SLIDES}
  createCarouselSlides:
    handler: src/handlers/carouselSlides/createCarouselSlides.handler
    events:
      - httpApi:
          path: /${self:provider.stage}/carouselSlides
          method: POST
          cors: true
    environment:
      TABLE_NAME_SLIDES: ${env:TABLE_NAME_SLIDES}
  getQuestions:
    handler: src/handlers/questions/queryQuestions.handler
    description: 'Get texts'
    events:
      - httpApi:
          path: /${self:provider.stage}/questions
          method: GET
          cors: true
    environment:
      TABLE_NAME_QUESTIONS: ${env:TABLE_NAME_QUESTIONS}
  createTexts:
    handler: src/handlers/questions/createQuestion.handler
    events:
      - httpApi:
          path: /${self:provider.stage}/questions
          method: POST
          cors: true
    environment:
      TABLE_NAME_QUESTIONS: ${env:TABLE_NAME_QUESTIONS}
  login:
    handler: src/handlers/auth/auth.login
    events:
      - httpApi:
          path: /${self:provider.stage}/login
          method: POST
          cors: true
    environment:
      TABLE_NAME_AUTH: ${env:TABLE_NAME_AUTH}
      JWT_SECRET: ${env:JWT_SECRET}
  verifyToken:
    handler: src/handlers/auth/auth.validate

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: isActive
            AttributeType: N
          - AttributeName: firstName
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: isActiveIndex
            KeySchema:
              - AttributeName: isActive
                KeyType: HASH
              - AttributeName: firstName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3
          - IndexName: userNameIndex
            KeySchema:
              - AttributeName: userName
                KeyType: HASH
              - AttributeName: firstName
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3
    carouselSlidesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: carouselSlidesTable
        KeySchema:
          - AttributeName: carouselSlideId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: carouselSlideId
            AttributeType: S
          - AttributeName: isActiveSlide
            AttributeType: N
          - AttributeName: sortIndex
            AttributeType: N
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: isActiveSlideIndex
            KeySchema:
              - AttributeName: isActiveSlide
                KeyType: HASH
              - AttributeName: sortIndex
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3
    questionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: questionsTable
        KeySchema:
          - AttributeName: questionId
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: questionId
            AttributeType: S
          - AttributeName: isActive
            AttributeType: N
          - AttributeName: sortIndex
            AttributeType: N  
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: isActiveQuestionsIndex
            KeySchema:
              - AttributeName: isActive
                KeyType: HASH
              - AttributeName: sortIndex
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3
    authTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: authTable
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1