plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb
  - serverless-offline
app: serverless-basic
service: serverless-basic
useDotenv: true
frameworkVersion: '3'

provider: ${file(./sls-yml/provider.yml)}

custom: ${file(./sls-yml/custom.yml)}

functions: ${file(./sls-yml/functions.yml)}

resources: ${file(./sls-yml/resources.yml)}